<script>
//var $j = jQuery.noConflict();
// Code that uses other library's $ can follow here.
</script>
<script src="" type="text/javascript" charset="utf-8"></script>
<script>
    $(document).ready(function ()
    {
        var options = {  
            url:        'contacts/email', 
            dataType: 'html',
            beforeSubmit: function()
            { 
               // $("#emsg").html('<img src="/images/photos/loading.gif" width="20" height="20" >');
            },
            
            success:    function(data) { 
           
                $('#msg').html(data);

                $('#msg').delay(2000).fadeOut();
                
               $("#contactus_form")[0].reset();
            } 
        }; 
   
        $('#contactus_form').ajaxForm(options);
    });
</script>
<style type="text/css">
    .widget111 
    {
        background-color:#FFFFFF;
        background-position:initial initial;
        background-repeat:initial initial;
        border:1px solid #EEEEEE;
        margin-bottom:10px;
        padding:8px 10px;

        border-top-color:#FF5D5E;
        border-top-style:solid;
        border-top-width:1px;
        height: 118px;
    }

</style>
<?php
foreach ($listPagesDatas as $key => $value)
{
    $tit[]= $value['title'];
    $subtit[]= $value['sub_title'];
    $status[]= $value['status'];
    $discrip[]= $value['description'];
}
?>


<div class="page-head">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <?php
                foreach ($listMenuDatasImageContacts as $key => $value)
                {
                    if($value['image']!= '')
                    {
                    ?>
                        <img src="/images/products/menu/<?php echo $value['image'];?>" class="img-responsive"/>
                    <?php
                    }
                    else
                    {
                    ?>
                        <img src="/images/photos/suprt_bnr.jpg" class="img-responsive">
                    <?php
                    }
                }
        ?>
      </div>
    </div>
  </div>
</div>

<!-- banner starts -->

<!-- sublink starts -->

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="posts">
                <div class="tags">
                    <a href="/contacts" class="active"><?php echo $tit[0]; ?></a> <a href="/contacts/aboutUs"><?php echo $tit[1]; ?></a>  <!-- <a href="#">Why You Should go responsive</a>-->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- sublink ends -->

<!-- content area -->

<div class="content blog">
    <div class="container">
        <div class="row">
            <!-- first column starts -->
            <div class="col-md-8">
                <div class="posts">
                    <div class="entry">
                        <h2><a href="#"><?php echo $tit[0]; ?></a></h2>
                        <?php
                        $c= count($listContactusDatas);
                        foreach ($listContactusDatas as $key => $value)
                        {
                          $title[]= $value['title'];
                          $dis[]= $value['description'];
                          $country[]= $value['country'];
                          $phone[]= $value['phone'];
                          $service[]= $value['service_email'];
                         
                        }
                       
                        ?>
                        <h4><?php echo $subtit[0]?></h4>
                        <p><?php echo $discrip[0]?></p>
                        <br>
                        <div class="cwell">
                            <img src="/images/photos/contactUs.png" class="img-responsive pull-left width"> 
                        </div>
        
                        <div class="cwell">
                            <!-- Address section -->
                            <h4 class="title">Customer Care</h4>
                    
                            <div class="address">
                                <address>
                                    <!-- Address -->
                                    <?php
                                    for($i= 0; $i<= $c-1; $i++)
                                    {
                                      echo "<div style='width:200px;float:left;'><span style='width:55px; float:left;'>".ucfirst($country[$i])."</span>"."<span style='font-size:12px;float:left; width:10px;'>".':'."</span><span style='width:90px; float:left;'>".$phone[$i]."</span></div>";

                                    }
                                    ?>
                                   
                                    <!-- Phone number -->
                                </address>
                                 <br>
                                <address>
                                <div style='width:200px;float:left;'>
                                    <!-- Name -->
                                    <strong>E-mail</strong><br>
                                    <!-- Email --> 
                                    <a href="mailto:#"><?php echo $service[1]?></a>
                                </div>
                                </address>
                                <!-- Social media icons -->
                                <div style='width:200px;float:left;'>
                                    <strong>Get in touch:</strong>
                                    <div class="social">
                                        <a href="http://www.facebook.com"><i class="icon-facebook facebook"></i></a>
                                        <a href="http://www.twitter.com"><i class="icon-twitter twitter"></i></a>
                                        <a href="http://www.linkedin.com"><i class="icon-linkedin linkedin"></i></a>
                                        <a href="http://www.gooleplus.com"><i class="icon-google-plus google-plus"></i></a>
                                        <a href="http://www.pintrust.com/"><i class="icon-pinterest pinterest"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <!--<div class="gmap" style="margin-top:30px;">
                    <!-- Google Maps. Replace the below iframe with your Google Maps embed code 
                    <iframe height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Google+India+Bangalore,+Bennigana+Halli,+Bangalore,+Karnataka&amp;aq=0&amp;oq=google+&amp;sll=9.930582,78.12303&amp;sspn=0.192085,0.308647&amp;ie=UTF8&amp;hq=Google&amp;hnear=Bennigana+Halli,+Bangalore,+Bengaluru+Urban,+Karnataka&amp;t=m&amp;ll=12.993518,77.660294&amp;spn=0.012545,0.036006&amp;z=15&amp;output=embed"></iframe>
                </div>-->
            </div>
            <!-- first column ends -->
            <div class="col-md-4">
                <!-- Sidebar -->
                <div class="sidebar">
                    <!-- Widget -->
                    <div class="widget">
                        <h4>Yes, please contact and tell Us more:</h4>
                        <div id="emsg" style="font-size:12px; float:right; color:red;"></div>
                        <div id="msg" style="font-size:12px; float:right; color:red;"></div>
                        <form class="form-inline" role="form" name="contactus_form" id="contactus_form" method="post" action="contacts" >
                            <div class="form-group">
                                <input type="text" class="form-control mar_top" id="company" name="company" placeholder="Company Name..." required>
                                <input type="text" class="form-control mar_top" id="cp" name="cp" placeholder="Contact Person..." required>
                                <input type="text" class="form-control mar_top" id="phone" name="phone" placeholder="Phone Number..." required>
                                <input type="email" class="form-control mar_top" id="email" name="email" placeholder="Email..." required>
                            </div>
                            <h5>Iam Most Interested in</h5>
                            <div class="checkbox" >
                                <label>
                                    <input type="checkbox" id="ch1" name="ch1" value="Homepage"> Homepage
                                </label>
                            </div>
          
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="ch2" name="ch2" value="Homepage Mobile"> Homepage Mobile
                                </label>
                            </div>
                   
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="ch3" name="ch3" value="Homepage Responsive"> Homepage Responsive
                                </label>
                            </div>
                    
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="ch4" name="ch4" value="E-Commerse"> E-Commerse
                                </label>
                            </div>
          
                            <div class="selectbox">
                                <select class="form-control" id="sel" name="sel">
                                    <option value="">Please select..</option>
                                    <option value="CMS">CMS</option>
                                    <option value="Wordpress">Wordpress</option>
                                </select>
                            </div>                                  

                            <button type="submit"  class="btn btn-danger mar_top">Send</button>
                        </form>
                    </div>
            
                    <div class="widget111">
                        <h4>Contact Us</h4>
                        <?php
                        for($i= 0; $i<= $c-1; $i++)
                        {
                            ?>
                            <div style='width:200px;float:left;'>
                                <span style='width:55px; float:left;'>
                                    <?php
                                        if($country[$i] == "Sweden")
                                        {
                                          echo "Sverige";
                                        }
                                        else
                                        {
                                          echo ucfirst($country[$i]);
                                        }
                                    ?>
                                </span>
                                <span style='font-size:12px;float:left; width:10px;'>:</span>
                                <span style='width:90px; float:left;'><?php echo $phone[$i] ?></span>
                            </div>
                        <?php
                        }
                        ?>

                    </div> 
                    
                    <div class="widget">
                        <h4>We will help you succeed on the Web</h4>
                        <p>We create a website for your needs at a good price.</p>
                        <p class="bold">Get a great looking website today!</p>
                    </div>
                </div>
                <!-- Sidebar ends -->                                                
            </div>
            <!-- colmd4 ends -->
        </div>
        <!-- row ends -->
    </div>
    <!-- container ends -->
</div>
<!-- content blog ends -->

<!-- Footer starts -->
