<script src="/js/jquery.validate.js"></script>


<script>
$().ready(function() {
    // validate the comment form when it is submitted
    $("#commentForm").validate();

    // validate signup form on keyup and submit
    $("#addProduct").validate({
        rules: {
            specification: "required",
            
        },
        messages: {
            specification: "Specification Please",           
          
        }
                    
    }) 
    
});
</script>


<style type="text/css">
#commentForm { width: 500px; }
#commentForm label { width: 250px; }
#commentForm label.error, #commentForm input.submit { margin-left: 253px; }
#signupForm { width: 670px; }
#signupForm label.error {
    margin-left: 10px;
    width: auto;
    display: inline;
}
#newsletter_topics label.error {
    display: none;
    margin-left: 103px;
}
.errors{color:red;}
</style>

<div class="span12" id="content">
    <div class="row-fluid">

        <div class="navbar">
            <div class="navbar-inner">
                <ul class="breadcrumb">
                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <li>
                        <a href="">Dashboard</a> <span class="divider">/</span> 
                    </li>
                    <li>
                        <a href="">Home</a> <span class="divider">/</span>  
                    </li>
                    <li class="active"><a href="" >Add Website Package</a>
                            <span style="font-size:12px;color:red;">
                                <?php
                                if(count($flashMessages))
                                {
                                    foreach ($flashMessages as $msg)
                                    {
                                        echo $msg.'</blink><br>';   
                                    }   
                                }
                                ?>
                            </span>
                    </li>
                </ul>
            </div>
        </div>

        <a class="btn btn-primary " href="/admin/ecommercePackage">List Website Package</a>
        <!--<a class="btn btn-primary " href="/superadmin/slider/add" border="0">Add slider</a>-->
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Specification Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Specification</label>
                                    <div class="controls">
                                        <input type="text" name="specification" id="specification" class="span6" id="typeahead" ><br />
                                    </div>
                                </div>
                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/website";
    });

</script>