<script type="text/javascript">

    
    $(document).ready(function() {
        showTable();
        //$("#ajx_table").html('wt the fk');

    });
    
    function showTable()
    {
        
        $.ajax({
            type:"POST",
            url:"/admin/ecommercePackage/ajaxList",
            cache:false,
            data:{},
            dataType:"html",
            success:function(data)
            {
                //alert(data);//return;
                $("#ajx_table").html(data);
                //showTable(srt);
            }
        });
    }

       
    
    //Status off
    $('.ston').live('click',function()
    {
        var offId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/ecommercePackage/status",
            cache:false,
            data:{offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

    //Status On
    $('.stof').live('click',function()
    {
        var onId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/ecommercePackage/status",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

   
    //delete function
    $('.del').live('click',function()
    {
        var delid = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/ecommercePackage/delete",
            cache:false,
            data:{ delid:delid },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

    function ajxUpdateDispOrder(id,order)
     {   
        alert(id); alert(order);
        $('#ajx_result_'+idVar).html('<img src="../images/10.gif" width="25" height="25" style="padding-bottom:10px;" >');
         
        $.ajax({
            url: "/admin/ecommercePackage/updateMenuOrder",
            type: "POST",
            cache: "false",
            data: 'id='+idVar+'&order='+disp_order,
            
            success: function(returnVal){                
                $('#ajx_result_'+idVar).html(returnVal);
                history.go(0);
            },
            error:function(){
 
            }   
        });
        
        //tTimeout('clear_span_msg();',3400);
    }   


</script>



<style type="text/css">
    .ston { cursor: pointer;} .stof { cursor: pointer;} .del { cursor: pointer;}

</style>

<div class="span12" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	<div class="navbar-inner">
	            <ul class="breadcrumb">
	                <i class="icon-chevron-left hide-sidebar">
                        <a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a>
                    </i>
	                <i class="icon-chevron-right show-sidebar" style="display:none;">
                        <a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a>
                    </i>
	                <li>
	                    <a href="">Dashboard</a> <span class="divider">/</span>	
	                </li>
	                <li>
	                    <a href="">Home</a> <span class="divider">/</span>	
	                </li>
	                <li class="active">Specification</li>
	            </ul>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Website Package widget</div>
                    <div id="msg" style="font-size:12px; color:red; text-align:center;"></div>
                    <a href="/admin/website/addPackage" style="text-decoration:none; float:right; margin-bottpm:8px;"><img src="/images/plus.png" width="" height="" border="0"></a>
                    <div class="pull-right">
                        <span class="badge badge-info"></span>
                    </div>
                </div>
                <div id="~ajx_table~"></div>
            </div>
        </div>
    </div>
                 