
<?php foreach ($webpackages as $webpackage)?>

<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>-->
<script>
var isDelete = 0;    
function deleteSpec(id){ 
    isDelete = 1;
    var conf= confirm("Sure Delete?");
    if(conf==true){
        $.ajax({
            type:"POST",
            url :"<?php echo $this->basePath().'/admin/specification/delete'?>",
            data:{specId:id},
            success:function(data){
                location.reload();
            },
            error:function(){
                alert('Error');
            },
        });
    }
//    else{
//        $.ajax({
//            type:"POST",
//            url :"<?php //echo $this->basePath().'/admin/specification/index'?>",
//            data:{specId:id},
//            success:function(data){
//                location.reload();
//            },
//            error:function(){
//                alert('Error');
//            },
//        });
//    }
}

</script>


<script type="text/javascript">
    
$(document).ready(function(){
 $(".editbox").hide();
$(".edit_tr").click(function(){
  
var ID=$(this).attr('id');

$("#pageHead"+ID).hide();
$("#pageDesc"+ID).hide();

$("#setupfee"+ID).hide();
$("#monthlycost"+ID).hide();
$("#marketprice"+ID).hide();
$("#specihead"+ID).hide();

$("#pkg_one_name"+ID).hide();
$("#pkg_two_name"+ID).hide();
$("#pkg_three_name"+ID).hide();

$("#pkg_one_link"+ID).hide();
$("#pkg_two_link"+ID).hide();
$("#pkg_three_link"+ID).hide();

$("#first_fee_kr"+ID).hide();
$("#first_fee_euro"+ID).hide();
$("#second_fee_kr"+ID).hide();
$("#second_fee_euro"+ID).hide();
$("#third_fee_kr"+ID).hide();
$("#third_fee_euro"+ID).hide();

$("#first_cost_kr"+ID).hide();
$("#first_cost_euro"+ID).hide();
$("#second_cost_kr"+ID).hide();
$("#second_cost_euro"+ID).hide();
$("#third_cost_kr"+ID).hide();
$("#third_cost_euro"+ID).hide();

$("#first_market_kr"+ID).hide();
$("#first_market_euro"+ID).hide();
$("#second_market_kr"+ID).hide();
$("#second_market_euro"+ID).hide();
$("#third_market_kr"+ID).hide();
$("#third_market_euro"+ID).hide();


$("#pageHead_"+ID).show();
$("#pageDesc_"+ID).show();

$("#setupfee_"+ID).show();
$("#monthlycost_"+ID).show();
$("#marketprice_"+ID).show();
$("#specihead_"+ID).show();

$("#pkg_one_name_"+ID).show();
$("#pkg_two_name_"+ID).show();
$("#pkg_three_name_"+ID).show();

$("#pkg_one_link_"+ID).show();
$("#pkg_two_link_"+ID).show();
$("#pkg_three_link_"+ID).show();

$("#first_fee_kr_"+ID).show();
$("#first_fee_euro_"+ID).show();
$("#second_fee_kr_"+ID).show();
$("#second_fee_euro_"+ID).show();
$("#third_fee_kr_"+ID).show();
$("#third_fee_euro_"+ID).show();

$("#first_cost_kr_"+ID).show();
$("#first_cost_euro_"+ID).show();
$("#second_cost_kr_"+ID).show();
$("#second_cost_euro_"+ID).show();
$("#third_cost_kr_"+ID).show();
$("#third_cost_euro_"+ID).show();

$("#first_market_kr_"+ID).show();
$("#first_market_euro_"+ID).show();
$("#second_market_kr_"+ID).show();
$("#second_market_euro_"+ID).show();
$("#third_market_kr_"+ID).show();
$("#third_market_euro_"+ID).show();

}).change(function(){
var ID=$(this).attr('id');

var page_head=$("#pageHead_"+ID).val();
var page_desc=$("#pageDesc_"+ID).val();

var setupfee=$("#setupfee_"+ID).val();
var monthlycost=$("#monthlycost_"+ID).val();
var marketprice=$("#marketprice_"+ID).val();
var specihead=$("#specihead_"+ID).val();

var pkg_one_name=$("#pkg_one_name_"+ID).val();
var pkg_two_name=$("#pkg_two_name_"+ID).val();
var pkg_three_name=$("#pkg_three_name_"+ID).val();

var pkg_one_link=$("#pkg_one_link_"+ID).val();
var pkg_two_link=$("#pkg_two_link_"+ID).val();
var pkg_three_link=$("#pkg_three_link_"+ID).val();

var first_fee_kr=$("#first_fee_kr_"+ID).val();
var first_fee_euro=$("#first_fee_euro_"+ID).val();
var second_fee_kr=$("#second_fee_kr_"+ID).val();
var second_fee_euro=$("#second_fee_euro_"+ID).val();
var third_fee_kr=$("#third_fee_kr_"+ID).val();
var third_fee_euro=$("#third_fee_euro_"+ID).val();

var first_cost_kr=$("#first_cost_kr_"+ID).val();
var first_cost_euro=$("#first_cost_euro_"+ID).val();
var second_cost_kr=$("#second_cost_kr_"+ID).val();
var second_cost_euro=$("#second_cost_euro_"+ID).val();
var third_cost_kr=$("#third_cost_kr_"+ID).val();
var third_cost_euro=$("#third_cost_euro_"+ID).val();

var first_market_kr=$("#first_market_kr_"+ID).val();
var first_market_euro=$("#first_market_euro_"+ID).val();
var second_market_kr=$("#second_market_kr_"+ID).val();
var second_market_euro=$("#second_market_euro_"+ID).val();
var third_market_kr=$("#third_market_kr_"+ID).val();
var third_market_euro=$("#third_market_euro_"+ID).val();

//document.write(ID);

var dataString = 'id='+'<?php echo $webpackage['id'];?>'+'&pageHead='+page_head+'&pageDesc='+page_desc+'&setupfee='+setupfee+'&monthlycost='+monthlycost+'&marketprice='+marketprice+'&specihead='+specihead+'&packageFirst='+pkg_one_name+'&packageSecond='+pkg_two_name+'&packageThird='+pkg_three_name+'&pkgOneLink='+pkg_one_link+'&pkgTwoLink='+pkg_two_link+'&pkgThreeLink='+pkg_three_link+'&firstFeeKr='+first_fee_kr+'&firstFeeEuro='+first_fee_euro+'&secondFeeKr='+second_fee_kr+'&secondFeeEuro='+second_fee_euro+'&thirdFeeKr='+third_fee_kr+'&thirdFeeEuro='+third_fee_euro+'&firstCostKr='+first_cost_kr+'&firstCostEuro='+first_cost_euro+'&secondCostKr='+second_cost_kr+'&secondCostEuro='+second_cost_euro+'&thirdCostKr='+third_cost_kr+'&thirdCostEuro='+third_cost_euro+'&firstMarketKr='+first_market_kr+'&firstMarketEuro='+first_market_euro+'&secondMarketKr='+second_market_kr+'&secondMarketEuro='+second_market_euro+'&thirdMarketKr='+third_market_kr+'&thirdMarketEuro='+third_market_euro;

//if(first.length && last.length>0)
//{
    //alert('hi');
$.ajax({
type: "POST",
url: "<?php echo $this->basePath().'/admin/website/editAjax';?>" ,
data: dataString,
cache: false,
beforeSend:function(){
    $("#first_"+ID).html('<img src=<?php echo $this->basePath().'/images/'?>load_rs.gif />');
},
success: function(html){
//alert(html);    
$("#pageHead"+ID).html(page_head);    
$("#pageDesc"+ID).html(page_desc); 

$("#setupfee"+ID).html(setupfee);
$("#monthlycost"+ID).html(monthlycost);
$("#marketprice"+ID).html(marketprice);
$("#specihead"+ID).html(specihead);

$("#pkg_one_name"+ID).html(pkg_one_name);   
$("#pkg_two_name"+ID).html(pkg_two_name); 
$("#pkg_three_name"+ID).html(pkg_three_name); 
   
$("#first_fee_kr"+ID).html(first_fee_kr+' Kr');
$("#first_fee_euro"+ID).html('('+first_fee_euro+' Euro)');
$("#second_fee_kr"+ID).html(second_fee_kr+' Kr');
$("#second_fee_euro"+ID).html('('+second_fee_euro+' Euro)');
$("#third_fee_kr"+ID).html(third_fee_kr+' Kr');
$("#third_fee_euro"+ID).html('('+third_fee_euro+' Euro)');

$("#first_cost_kr"+ID).html(first_cost_kr+' Kr');
$("#first_cost_euro"+ID).html('('+first_cost_euro+' Euro)');
$("#second_cost_kr"+ID).html(second_cost_kr+' Kr');
$("#second_cost_euro"+ID).html('('+second_cost_euro+' Euro)');
$("#third_cost_kr"+ID).html(third_cost_kr+' Kr');
$("#third_cost_euro"+ID).html('('+third_cost_euro+' Euro)');

$("#first_market_kr"+ID).html(first_market_kr+' Kr');
$("#first_market_euro"+ID).html('('+first_market_euro+' Euro)');
$("#second_market_kr"+ID).html(second_market_kr+' Kr');
$("#second_market_euro"+ID).html('('+second_market_euro+' Euro)');
$("#third_market_kr"+ID).html(third_market_kr+' Kr');
$("#third_market_euro"+ID).html('('+third_market_euro+'Euro)');
location.reload();
},
error:function(){
    alert('error');
},
});
//}
//else
//{
//alert('Enter something.');
//}

});

$(".editbox").mouseup(function() 
{
return false
});

$(document).mouseup(function()
{
$(".editbox").hide();
$(".text").show();
});

});
</script>


<script type="text/javascript">

$(document).ready(function()
{$(".editbox").hide();
$("tr.edit_tr2").click(function(){
    if(isDelete) { isDelete = 0; return; }
   //  $(".edit_tr2 td:last-child").click(function()){$(".editbox").hide();}
var ID=$(this).attr('id');

$("#specification"+ID).hide();
$("#package_one"+ID).hide();
$("#package_two"+ID).hide();
$("#package_three"+ID).hide();

$("#specification_"+ID).show();
$("#package_one_"+ID).show();
$("#package_two_"+ID).show();
$("#package_three_"+ID).show();


}).change(function(){
var ID=$(this).attr('id');

var specification=$("#specification_"+ID).val();
var package_one  =$("#package_one_"+ID).val();
var package_two  =$("#package_two_"+ID).val();
var package_three=$("#package_three_"+ID).val();

//document.write(ID);
var dataString = 'id='+ID+'&specification='+specification+'&packageOne='+package_one+'&packageTwo='+package_two+'&packageThree='+package_three;

//if(first.length && last.length>0)
//{
    //alert('hi');
$.ajax({
type: "POST",
url: "<?php echo $this->basePath().'/admin/specification/editAjax';?> " ,
data: dataString,
cache: false,
beforeSend:function(){
    $("#specification_"+ID).html('<img src=<?php echo $this->basePath().'/images/'?>load_rs.gif />');
},
success: function(html){
    //alert(html);    
$("#specification"+ID).html(specification);  
$("#package_one"+ID).html(package_one); 
$("#package_two"+ID).html(package_two); 
$("#package_three"+ID).html(package_three); 

},
error:function(){alert('error');
},
});
//}
//else
//{
//alert('Enter something.');
//}

});

$(".editbox").mouseup(function() 
{
return false
});

$(document).mouseup(function()
{
$(".editbox").hide();
$(".text").show();
});

});


$(function() {
        var scntDiv = $('#p_scents');
        var i = $('#p_scents tr').size() + 1;
        $('#rs_button').hide();
        $('#addScnt').live('click', function() {
        $('#rs_button').show();
$('<tr><td width="25%"><label for="p_scnts"><input type="text" id="p_scnt" size="0" name="p_scnt[]" value="" placeholder="Input Value" style="width:90%;" /></label></td><td width="25%"><label for="p_scnts"><input type="text" id="p_scnt1" size="0" name="p_scnt1[]" value="" placeholder="Input Value" style="width:70%;" /></label></td><td width="25%"><label for="p_scnts"><input type="text" id="p_scnt2" size="0" name="p_scnt2[]" value="" placeholder="Input Value" style="width:70%;"/></label></td><td colspan="2" width="25%"><label for="p_scnts"><input type="text" id="p_scnt3" size="0" name="p_scnt3[]" value="" placeholder="Input Value" style="width:70%;float:left;"/><h2 style="float:left; margin:0 0 0 0;"><a href="#" id="remScnt"><img src="<?php echo $this->basePath()."/images/minus.png";?>" title="Remove Row"></a></h2></label></td></tr>').appendTo(scntDiv);
                i++;
                return false;
        });
        
        $('#remScnt').live('click', function() { 
                if( i > 1) {
                        $(this).parents('tr').remove();
                        i--;
                }
                if(i==1){                
                        $('#rs_button').hide();
                }
                return false;
        });
});

</script>

<script>
function addMoreSpec(){
//    var values = [];
//    $('input[name="p_scnt[]"]').each(function() {
//    values.push($(this).val());

//});
//alert(values);
    var specific = $('input[name="p_scnt[]"]').map(function() {
        return this.value;
    }).get();
    
    var detail1 = $('input[name="p_scnt1[]"]').map(function() {
        return this.value;
    }).get();
    
    var detail2 = $('input[name="p_scnt2[]"]').map(function() {
        return this.value;
    }).get();
    
    var detail3 = $('input[name="p_scnt3[]"]').map(function() {
        return this.value;
    }).get();
    
    $.ajax({
        type :"POST",
        url  :"<?php echo $this->basePath().'/admin/specification/add'?>",
        cache:'false',
        data :{spec:specific,details1:detail1,details2:detail2,details3:detail3},
        beforeSend:function(){
               $("#specific_rs").html('<img src=<?php echo $this->basePath().'/images/'?>load_rs.gif  />');              
        },
        success:function(data){
            //alert(data);
            $("#specific_rs").html('');
            location.reload();
        },
        error:function(){
            alert('Error');
        },
        
    });
   
} 
</script>

<style>
body
{
font-family:Arial, Helvetica, sans-serif;
font-size:14px;
}
.editbox
{
display:none;
}
td
{
padding:7px;
}
.editbox
{
font-size:14px;
width:270px;
background-color:#ffffcc;
width:150px;
border:solid 1px #000;
padding:4px;
}
.edit_td:hover
{
background:url(<?php echo $this->basePath().'/images/';?>edit_rs.png) right no-repeat #80C8E5;
cursor:pointer;
}
th
{
font-weight:bold;
text-align:left;
padding:4px;
}
.head
{
background-color:#333;
color:#FFFFFF;
}

</style>


<style type="text/css">
   // .ston { cursor: pointer;} .stof { cursor: pointer;} .del { cursor: pointer;}

</style>

<div class="span12" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	<div class="navbar-inner">
	            <ul class="breadcrumb">
	                <i class="icon-chevron-left hide-sidebar">
                        <a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a>
                    </i>
	                <i class="icon-chevron-right show-sidebar" style="display:none;">
                        <a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a>
                    </i>
	                <li>
	                    <a href="">Dashboard</a> <span class="divider">/</span>	
	                </li>
	                <li>
	                    <a href="">Home</a> <span class="divider">/</span>	
	                </li>
	                <li class="active">Website Packages</li>
	            </ul>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            	<div class="comments well">
                    
             <table class="table table-bordered">
                 <tr id="2" class="edit_tr">
                     <td>Page Heading </td>
                     <td colspan="3" class="edit_td">
                         <span id="pageHead2" class="text"><?=$webpackage['title'];?></span>
                         <input style="width:500px;" type="text" value="<?=$webpackage['title'];?>" class="editbox" id="pageHead_2" />
                     </td>
                 </tr>
                 <tr id='3' class="edit_tr">
                     <td>Description</td>
                     <td colspan="4" class="edit_td">
                         <span id="pageDesc3" class="text"><?=$webpackage['description'];?></span>                       
                         <textarea style="width:500px; height: 100px;" class="editbox" name="Description" id="pageDesc_3"><?=$webpackage['description'];?></textarea></td>
                 </tr>
                 <tr id="" style="background:#eee;" class="">
                          <td></td>
                          
                           <td>  <ul class="comment-list ">
				<div class="comment pull-right">
<!--                                    <div id="upload"></div>-->
                                  
			        <a class="" href="#">
				<?php						
					if($webpackage['package_one_image']=='') {
				?>		
                                        <img class="avatar" src="img/photos/home_pls.gif" alt="" />
				<?php }
					else {
				?>
                                        <img class="avatar" src="<?php echo $this->basePath().'/images/products/web_package/'.$webpackage['package_one_image'];?>" alt="" width="154" height="103"/>
					
				<?php 
				       }
				?>
				</a>
                                   <form>
                                            <input style="width:200Px; display: none;" id="image_rs1" type="file" name="fileimg1" onchange="fileUpload(this.form,'<?php echo $this->basePath().'/admin/website/editImage';?>','<?php echo $this->basePath().'/images/products/web_package/';?>'); return false;">
                                            <input type="hidden" name="packageId" value="<?=$webpackage['id'];?>" /><br>
                                            <a style="width:100%;" onclick="$('input[id=image_rs1]').click();">Click to edit image</a>
              <!--<input name type="button" value="upload" onClick="fileUpload(this.form,'<?php //echo $this->basePath().'/admin/website/editImage';?>','<?php //echo $this->basePath().'/images/products/web_package/';?>'); return false;" >-->                               
                                   </form>
                                       <div class="comment-author"><a href="#"><?=$webpackage['package_one_name'];?></a></div>
                                </div>
					
                                   
                               </ul></td>
            
                         <td><ul class="comment-list">
				<div class="comment pull-right">
				 <a class="" href="#">
				<?php						
					if($webpackage['package_two_image']=='') {
				?>		
                                        <img class="avatar" src="img/photos/home_pls.gif" alt="" />
				<?php }
					else {
				?>
                                        <img class="avatar" src="<?php echo $this->basePath().'/images/products/web_package/'.$webpackage['package_two_image'];?>" alt="" width="154" height="103"/ />
					
				<?php 
				       }
				?>
				</a>
                                     <form><input style="width:200Px; display: none;" id="image_rs2" type="file" name="fileimg2" onchange="fileUpload(this.form,'<?php echo $this->basePath().'/admin/website/editImage';?>','<?php echo $this->basePath().'/images/products/web_package/';?>'); return false;">
                                            <input type="hidden" name="packageId" value="<?=$webpackage['id'];?>" /><br>
                                             <a style="width:100%;" onclick="$('input[id=image_rs2]').click();">Click to edit image</a>
                         <!--<input name type="button" value="upload" onClick="fileUpload(this.form,'<?php //echo $this->basePath().'/admin/website/editImage';?>','<?php //echo $this->basePath().'/images/products/web_package/';?>'); return false;" >-->
                                 </form>       
                                       <div class="comment-author hidden-xs"><a href="#"><?=$webpackage['package_two_name'];?></a></div> 
                                    <div id="upload_iframe"></div>
                                </div>
                                 
                                 
			    </ul></td>
                            <td> <ul class="comment-list">
				<div class="comment pull-right">
				 <a class="" href="#">
				   <?php						
					if($webpackage['package_three_image']=='') {
				    ?>		
                                        <img class="avatar" src="img/photos/home_pls.gif" alt="" />
				<?php }
					else {
				 ?>
                                        <img class="avatar" src="<?php echo $this->basePath().'/images/products/web_package/'.$webpackage['package_three_image'];?>" alt="" width="154" height="103"/ />
					
				<?php 
				       }
				 ?>
				</a>
                                   <form><input style="width:200Px; display: none;" id="image_rs3" type="file" name="fileimg3" onchange="fileUpload(this.form,'<?php echo $this->basePath().'/admin/website/editImage';?>','<?php echo $this->basePath().'/images/products/web_package/';?>'); return false;">
                                       <input type="hidden" name="packageId" value="<?=$webpackage['id'];?>" /><br>
                                            <a style="width:100%;" onclick="$('input[id=image_rs3]').click();">Click to edit image</a>
                                        <!--<input name type="button" value="upload" onClick="fileUpload(this.form,'<?php //echo $this->basePath().'/admin/website/editImage';?>','<?php //echo $this->basePath().'/images/products/web_package/';?>'); return false;" >-->
                                    </form>
                                  <div class="comment-author hidden-xs"><a href="#"><?=$webpackage['package_three_name'];?></a></div>  
                                </div>
		                
                                   
			</ul></td>
                        <td style="border-left:none;"></td>
                        
                        
                        </tr>
                        
                        <tr id="4" class="edit_tr" style="background:#eee;">
                            <td class="edit_td">
                                <strong>
<span id="setupfee4" class="text"><?=$webpackage['setupfee'];?></span>
<input type="text" value="<?=$webpackage['setupfee'];?>" class="editbox" id="setupfee_4"/>
                                </strong>
                            </td>
                          <td class="edit_td">
<span id="first_fee_kr4" class="text"><?php if($webpackage['package_one_setupfee_kr'])echo $webpackage['package_one_setupfee_kr'].' Kr';?></span>
<span id="first_fee_euro4" class="text"><?php if($webpackage['package_one_setupfee_euro']) echo '('.$webpackage['package_one_setupfee_euro'].' Euro)';?></span>
<input type="text" value="<?=$webpackage['package_one_setupfee_kr'];?>" class="editbox" id="first_fee_kr_4" />
<input type="text" value="<?=$webpackage['package_one_setupfee_euro'];?>" class="editbox" id="first_fee_euro_4" />
                          </td>
                          <td class="edit_td">
<span id="second_fee_kr4" class="text"><?php if($webpackage['package_two_setupfee_kr'])echo $webpackage['package_two_setupfee_kr'].' Kr';?></span>
<span id="second_fee_euro4" class="text"><?php if($webpackage['package_two_setupfee_euro']) echo '('.$webpackage['package_two_setupfee_euro'].' Euro)';?></span>
<input type="text" value="<?=$webpackage['package_two_setupfee_kr'];?>" class="editbox" id="second_fee_kr_4" />
<input type="text" value="<?=$webpackage['package_two_setupfee_euro'];?>" class="editbox" id="second_fee_euro_4" />

                          </td>
                          <td class="edit_td" colspan="2">
<span id="third_fee_kr4" class="text"><?php if($webpackage['package_three_setupfee_kr'])echo $webpackage['package_three_setupfee_kr'].' Kr';?></span>
<span id="third_fee_euro4" class="text"><?php if($webpackage['package_three_setupfee_euro']) echo '('.$webpackage['package_three_setupfee_euro'].' Euro)';?></span>
<input type="text" value="<?=$webpackage['package_three_setupfee_kr'];?>" class="editbox" id="third_fee_kr_4" />
<input type="text" value="<?=$webpackage['package_three_setupfee_euro'];?>" class="editbox" id="third_fee_euro_4" />
                          </td>                         
                        </tr>                      
                     
                        <tr id="5" class="edit_tr" style="background:#eee;">
                          <td class="edit_td">
                              <strong>
<span id="monthlycost5" class="text"><?php echo $webpackage['monthlycost'];?></span>
<input type="text" value="<?=$webpackage['monthlycost'];?>" class="editbox" id="monthlycost_5"/>
                              </strong>
                          </td>
                          <td class="edit_td">
<span id="first_cost_kr5" class="text"><?php if($webpackage['package_one_monthlycost_kr']) echo $webpackage['package_one_monthlycost_kr'].' Kr';?></span>
<span id="first_cost_euro5" class="text"><?php if($webpackage['package_one_monthlycost_euro']) echo '('.$webpackage['package_one_monthlycost_euro'].' Euro)';?></span>
<input type="text" value="<?=$webpackage['package_one_monthlycost_kr'];?>" class="editbox" id="first_cost_kr_5" />
<input type="text" value="<?=$webpackage['package_one_monthlycost_euro'];?>" class="editbox" id="first_cost_euro_5" />

                          </td>
                          <td class="edit_td">
<span id="second_cost_kr5" class="text"><?php if($webpackage['package_two_monthlycost_kr']) echo $webpackage['package_two_monthlycost_kr'].' Kr';?></span>
<span id="second_cost_euro5" class="text"><?php if($webpackage['package_two_monthlycost_euro']) echo '('.$webpackage['package_two_monthlycost_euro'].' Euro)';?></span>
<input type="text" value="<?=$webpackage['package_two_monthlycost_kr'];?>" class="editbox" id="second_cost_kr_5" />
<input type="text" value="<?=$webpackage['package_two_monthlycost_euro'];?>" class="editbox" id="second_cost_euro_5" />

                          </td>
                          <td colspan="2" class="edit_td">
<span id="third_cost_kr5" class="text"><?php if($webpackage['package_three_monthlycost_kr']) echo $webpackage['package_three_monthlycost_kr'].' Kr';?></span>
<span id="third_cost_euro5" class="text"><?php if($webpackage['package_three_monthlycost_euro']) echo '('.$webpackage['package_three_monthlycost_euro'].' Euro)';?></span>
<input type="text" value="<?=$webpackage['package_three_monthlycost_kr'];?>" class="editbox" id="third_cost_kr_5" />
<input type="text" value="<?=$webpackage['package_three_monthlycost_euro'];?>" class="editbox" id="third_cost_euro_5" />                             

                          </td>                         
                         
                        </tr>
                        <tr id="6" class="edit_tr" style="background:#eee;">
                          <td width="25%" class="edit_td">
                              <strong>
<span id="marketprice6" class="text"><?=$webpackage['marketprice'];?></span>
<input type="text" value="<?=$webpackage['marketprice'];?>" class="editbox" id="marketprice_6"/>
                              </strong>
                          </td>
                          <td width="25%" class="edit_td">
<span id="first_market_kr6" class="text"><?php if($webpackage['package_one_marketplace_kr']) echo $webpackage['package_one_marketplace_kr'].' Kr';?></span>
<span id="first_market_euro6" class="text"><?php if($webpackage['package_one_marketplace_euro']) echo '('.$webpackage['package_one_marketplace_euro'].' Euro)';?></span>
<input type="text" value="<?=$webpackage['package_one_marketplace_kr'];?>" class="editbox" id="first_market_kr_6" />
<input type="text" value="<?=$webpackage['package_one_marketplace_euro'];?>" class="editbox" id="first_market_euro_6" /> 
                          </td>
                          <td width="25%" class="edit_td">
<span id="second_market_kr6" class="text"><?php if($webpackage['package_two_marketplace_kr']) echo $webpackage['package_two_marketplace_kr'].' Kr';?></span>
<span id="second_market_euro6" class="text"><?php if($webpackage['package_two_marketplace_euro']) echo '('.$webpackage['package_two_marketplace_euro'].' Euro)';?></span>
<input type="text" value="<?=$webpackage['package_two_marketplace_kr'];?>" class="editbox" id="second_market_kr_6" />
<input type="text" value="<?=$webpackage['package_two_marketplace_euro'];?>" class="editbox" id="second_market_euro_6" /> 
                          </td>
                          <td colspan="2" width="25%" class="edit_td">
<span id="third_market_kr6" class="text"><?php if($webpackage['package_three_marketplace_kr']) echo $webpackage['package_three_marketplace_kr'].' Kr';?></span>
<span id="third_market_euro6" class="text"><?php if($webpackage['package_three_marketplace_euro']) echo '('.$webpackage['package_three_marketplace_euro'].' Euro)';?></span>
<input type="text" value="<?=$webpackage['package_three_marketplace_kr'];?>" class="editbox" id="third_market_kr_6" />
<input type="text" value="<?=$webpackage['package_three_marketplace_euro'];?>" class="editbox" id="third_market_euro_6" /> 
                          </td>
                        </tr>                    
                        <tr><td colspan="5" style="height:10px; background-color:#FFF;"></td></tr>
                     
                        <tr id="7" class="edit_tr">
                          <td class="edit_td" width="25%" style="background:#ff5d5e; color:#FFF;">
                              <strong>
<span id="specihead7" class="text"><?=$webpackage['specification'];?></span>
<input type="text" value="<?=$webpackage['specification'];?>" class="editbox" id="specihead_7"/>
                              </strong>
                          </td>
                          <td class="edit_td" width="25%"  style="background:#ff5d5e;  color:#FFF;">
                            <strong>
<span id="pkg_one_name7" class="text"><?=$webpackage['package_one_name'];?></span>
<input type="text" value="<?=$webpackage['package_one_name'];?>" class="editbox" id="pkg_one_name_7"/><br>  
<!--<span id="pkg_one_link7" class="text"><?=$webpackage['package_one_link'];?></span>-->
Link<input type="text" value="<?=$webpackage['package_one_link'];?>" class="editbox" id="pkg_one_link_7" /> 
                            </strong>
                          </td>
                          <td class="edit_td" width="25%"  style="background:#ff5d5e;  color:#FFF;">                              
                            <strong>
<span id="pkg_two_name7" class="text"><?=$webpackage['package_two_name'];?></span>
<input type="text" value="<?=$webpackage['package_two_name'];?>" class="editbox" id="pkg_two_name_7" /><br> 
<!--<span id="pkg_two_link7" class="text"><?=$webpackage['package_two_link'];?></span>-->
Link<input type="text" value="<?=$webpackage['package_two_link'];?>" class="editbox" id="pkg_two_link_7" />
                            </strong>
                          </td>
                          <td colspan="2" class="edit_td" style="background:#ff5d5e;  color:#FFF;" width="25%">
                            <strong>
<span id="pkg_three_name7" class="text"><?=$webpackage['package_three_name'];?></span>
<input type="text" value="<?=$webpackage['package_three_name'];?>" class="editbox" id="pkg_three_name_7" /><br> 
<!--<span id="pkg_three_link7" class="text"><?=$webpackage['package_three_link'];?></span>-->
Link<input type="text" value="<?=$webpackage['package_three_link'];?>" class="editbox" id="pkg_three_link_7" /> 
                            </strong>
                          </td>
                        </tr>
                     <?php foreach($specifications as $specification){?>
                        <tr id="<?=$specification['id'];?>" class="edit_tr2">
                          <td class="edit_td">
<span id="specification<?=$specification['id'];?>" class="text"><?=$specification['pkg_specification'];?></span>
<input type="text" value="<?=$specification['pkg_specification'];?>" class="editbox" id="specification_<?=$specification['id'];?>" />                            

                          </td>
                          <td class="edit_td">
<span id="package_one<?=$specification['id'];?>" class="text"><?=$specification['package_one'];?></span>
<input type="text" value="<?=$specification['package_one'];?>" class="editbox" id="package_one_<?=$specification['id'];?>" />                           
                          </td>
                          <td class="edit_td">
<span id="package_two<?=$specification['id'];?>" class="text"><?=$specification['package_two'];?></span>
<input type="text" value="<?=$specification['package_two'];?>" class="editbox" id="package_two_<?=$specification['id'];?>" /> 
                          </td>
                          <td class="edit_td">
<span id="package_three<?=$specification['id'];?>" class="text"><?=$specification['package_three'];?></span>
<input type="text" value="<?=$specification['package_three'];?>" class="editbox" id="package_three_<?=$specification['id'];?>" /> 

                          </td>
                          <td style="width:2%;"><a onclick="deleteSpec(<?=$specification['id'];?>)" style="float:right;" href="#" id="remScnt"><img src="<?php echo $this->basePath()."/images/delete.gif";?>" title="Delete Row"></a></td>
                        </tr>
                       
                     <?php } ?>
                      
                        <tbody id="p_scents" class="rs_scents"></tbody>
              </table>
                    <div style="width:95%; height: auto; text-align: right; padding-right: 5%">
                    <p><div id="specific_rs"></div><a href="#" id="addScnt">Add new record<img src="<?php echo $this->basePath().'/images/plus.png';?>" alt="" title="Add More"></a></p>
                    <input type="button" name="" id="rs_button" value="Submit" style="margin-right:0%; width: 20%;" onclick="addMoreSpec()"/>
                    </div>
        </div>
        </div>
    </div>
    

<script language="Javascript">
function fileUpload(form, action_url, path) {
     // Create the iframe...
    var iframe = document.createElement("iframe");
    iframe.setAttribute("id", "upload_iframe");
    iframe.setAttribute("name", "upload_iframe");
    iframe.setAttribute("width", "0");
    iframe.setAttribute("height", "0");
    iframe.setAttribute("border", "0");
    iframe.setAttribute("style", "width: 0; height: 0; border: none;");
 
    // Add to document...
    form.parentNode.appendChild(iframe);
    window.frames['upload_iframe'].name = "upload_iframe";
 
    iframeId = document.getElementById("upload_iframe");
 
    // Add event...
    var eventHandler = function () {
 
            if(iframeId.detachEvent) iframeId.detachEvent("onload", eventHandler);
            else iframeId.removeEventListener("load", eventHandler, false);
 
            // Message from server...
            if (iframeId.contentDocument) {
                content = iframeId.contentDocument.body.innerHTML;
            } else if (iframeId.contentWindow) {
                content = iframeId.contentWindow.document.body.innerHTML;
            } else if (iframeId.document) {
                content = iframeId.document.body.innerHTML;
            }
            
            document.getElementById('upload').innerHTML = content;
            alert(content);
            // Del the iframe...
            // setTimeout('iframeId.parentNode.removeChild(iframeId)', 250);
        
        }
 
    if (iframeId.addEventListener) iframeId.addEventListener("load", eventHandler, true);
    if (iframeId.attachEvent) iframeId.attachEvent("onload", eventHandler);
 
    // Set properties of form...
    form.setAttribute("target", "upload_iframe");
    form.setAttribute("action", action_url);
    form.setAttribute("method", "post");
    form.setAttribute("enctype", "multipart/form-data");
    form.setAttribute("encoding", "multipart/form-data");
 
    // Submit the form...
    form.submit();
 
    document.getElementById('upload').innerHTML = "Uploading...";
    
}
</script>



