<script type="text/javascript">

    
    $(document).ready(function() {
        showTable();

    });
    
    function showTable()
    {
        
        $.ajax({

            type:"POST",
            url:"/admin/country/ajaxList",
            cache:false,
            data:{},
            dataType:"html",
            success:function(data)
            {
                //alert(data);
                $("#ajx_table").html(data);
                //showTable(srt);
            }
        });
    }
    //delete function
    $('.del').live('click',function()
    {
        var delid = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/country/delete",
            cache:false,
            data:{ delid:delid },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

    //Status off
    $('.ston').live('click',function()
    {
        var offId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/country/status",
            cache:false,
            data:{ offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

    //Status On
    $('.stof').live('click',function()
    {
        var onId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/country/status",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

</script>
<style>
    .del{cursor:pointer;}.ston{cursor:pointer;}.stof{cursor:pointer;}
</style>

<div class="span9" id="content">
    <div class="row-fluid">
        <div class="navbar">
            <div class="navbar-inner">
	            <ul class="breadcrumb">
	                <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
	                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
	                <li><a href="">Dashboard</a> <span class="divider">/</span></li>
	                <li><a href="">Home</a> <span class="divider">/</span></li>
	                <li class="active">Menu Management</li>

	            </ul>
            </div>
        </div>
			
        
		<a class="btn btn-primary pull-right" href="/admin/country/add" border="0">Add Menu</a>
    </div>
                    
                   
    <div class="row-fluid">
        <div class="span12" style="min-height:400px;">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">
                        Home Menu
                    </div>
                    <div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>
                    <div class="pull-right"><span class="badge badge-info"></span>
				</div>
            </div>
            <div id="ajx_table"></div>
        
    </div>
</div>
               