<style type="text/css">
	.cls
	{
		padding: 10px;
    	text-align: justify;
	}
</style>
<table border="0" width="100%">
	<tr>
		<td style="text-align:center;">
			Detailed Complaint History 
		</td>
	</tr>
	<tr>
		<td>
			&nbsp;
		</td>
	</tr>
	<tr>
		<td>
			&nbsp;
		</td>
	</tr>
	<?php
	foreach ($detailedListing as $key => $value)
	{
	?>
	<tr>
		<td>
			<table border="1" width="60%" style="margin:0 auto;" cellpadding="5">
				<tr>
					<td align="center" width="30%">Unique Id</td>
					<td class="cls" width="30%"><?php echo $value['uniqueId']; ?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">Name</td>
					<td class="cls" width="30%"><?php echo $value['firstName'] .' '. $value['LastName']; ?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">Family Name</td>
					<td class="cls" width="30%"><?php echo $value['familyName'];?></td>	
				</tr>
				<tr>
					<td colspan="2">
						<table width="100%">
							<tr>
								<td><h4>Contact Details</h4></td>
							</tr>
							<tr>
								<td>
									<table width="100%">
										<tr>
											<td>
												<?php
													foreach($listPhone as $index=> $data)
						                    		{
						                    		?>
													<tr>
														<td align="center" width="30%">Phone</td><td class="cls" width="30%"><?php echo $data['phone']; ?></td>
													</tr>
							            		<?php
							            	       	}
												?>
											</td>
										</tr>
										<?php
										foreach($listEmail as $index => $data)
	                					{
	                					?>
		                    				<tr>
		                    					<td align="center" width="30%">Email </td><td class="cls" width="30%"><?php echo $data['email']; ?></td>
		                    		       	</tr>                    
					            		<?php
					                    }
					            		?>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td align="center" width="30%">Problem Type</td>
					<td class="cls" width="30%"><?php echo $value['problemType'];?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">Product Type</td>
					<td class="cls" width="30%"><?php echo $value['productType'];?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">Customer Complaint</td>
					<td class="cls" width="30%" style="text-align:justify; padding:10px;">
						<?php echo $value['complaint'];?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">What have been Done</td>
					<td class="cls" width="30%" style="text-align:justify; padding:10px;"><?php echo $value['whenDone'];?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">Created Date</td>
					<td class="cls" width="30%"><?php echo $value['createdOn'];?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">Finishing Date</td>
					<td class="cls" width="30%"><?php echo $value['finishDate'];?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">Next call date</td>
					<td class="cls" width="30%"><?php echo $value['nextCall'];?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">Work Assign To</td>
					<td class="cls" width="30%"><?php echo $value['assignTo'];?></td>	
				</tr>
				<tr>
					<td align="center" width="30%">Work Status</td>
					<td class="cls" width="30%">
						<?php
						$s= $value['status'];
						if($s == 0)
						{
							echo "Pending";
						}
						else if($s == 1)
						{
							echo "Solved";
						}
						else if($s == 2)
						{
							echo "To Company";
						}
						?>
					</td>	
				</tr>
				<tr>
					<td align="right" colspan="2" width="30%"><a href="/service/list"><input type="button" value="Back"></a></td>	
				</tr>
			</table>
		</td>
	</tr>
	<?php
	}
	?>
</table>