<script src="/js/jquery-1.9.1.js"></script>
<script src="/js/jquery-ui.js"></script>
<script type="text/javascript" src="/js/cool.js"></script>
<link rel="stylesheet" href="/css/jquery-ui.css">
<head>
<script>
	//Date Picker
	$(function() {
		$( "#finishDate" ).datepicker({
				changeMonth: true,
				changeYear: true
		});
		
		$( "#nextCall" ).datepicker({
			changeMonth: true,
			changeYear: true
		});
	});
</script>
</head>
<form name="form1" id="form1" action="" method="post" >
	<table border="0" width="100%">
		<tr>
			<td align="center">
				Service Registration
			</td>
		</tr>
		<tr>
			<td></td>
		</tr>
		<tr>
			<td></td>
		</tr>
		<tr>
			<td></td>
		</tr>
		<tr>
			<td></td>
		</tr>
		<?php
		foreach ($editHistory as $key => $value)
		{
			//print_r($value); exit;
		?>
		<tr>
			<td>
				<table width="60%" style="margin:0 auto;" id="myTable" border="1">
					<tr>
						<td align="center" width="30%">First Name</td><td align="center" width="30%"><input type="text" name="firstName" id="firstName" value="<?php echo $value['firstName'];?>"></td>
					</tr>
					<tr>
						<td align="center" width="30%">Last Name</td><td align="center" width="30%"><input type="text" name="lastName" id="lastName" value="<?php echo $value['LastName'];?>"></td>
					</tr>
					<tr>
						<td align="center" width="30%">Family Name</td><td align="center" width="30%"><input type="text" name="familyName" id="familyName" value="<?php echo $value['familyName'];?>"></td>
					</tr>
					<tbody id="phoneDiv">
					<?php
					//if($editPhone->count()> 0)
                	//if(isset($editPhone['phone'])){
					//$ph = ''; 
					$count=$editPhone->count();
					if($count>0)
					{
	                    foreach($editPhone as $index=> $data)
	                    {
	                    	//for($i=1; $i<=$count; $i++)
	                    	//{
	                    		//
	                    		//if($ph!=$data['phone']){
		                    //?>
								<tr>
									<td align="center" width="30%">Phone<?php echo $i;?></td><td align="center"><input type="text" name="phone[]"  value="<?php echo $data['phone']; ?>"  /> </td>
									<input type="hidden" name="phoneId[]" value="<?php echo $data['id']; ?>">
								</tr>
		            		<?php
		            	//}
		            	//$ph=$data['phone'];
		            	//$i++;
		            	//	}
		            		
	                    }
	            		?>
	                	
            		<?php
            		}
            		else
            		{
            		?>
            			<tr>
							<td align="center" width="30%">Phone</td><td align="center" width="30%"><input type="text" name="phone[]" id="phone" style="margin-left:14px;"><a href="javascript:void(0);" title="Click here to add more Numbers" onclick="addNewRow('phoneDiv', 'phone',$('#phoneDiv tr').length);" >
							<img src="../img/plus.png" border="0"></a></td>
						</tr>
					<?php
					}
					?>
					</tbody> 
					<tbody id="emailDiv">

						

						<?php
						$count=$editEmail->count();
						if($count>0)
						{
	                		foreach($editEmail as $index => $data)
	                		{
	                		?>
		                    	<tr>
		                    		<td align="center" width="30%">Email </td><td align="center" width="30%"><input type="text" name="email[]" value="<?php echo $data['email']; ?>"/>
		                    		</td>
		                    		<input type="hidden" name="emailId[]" value="<?php echo $data['id']; ?>">
		                    	</tr>                    
		            		<?php
		                    }
		            		?>
		                    
		                <?php
		                }
		                else
		                {
	            		?>
	            			<tr>
								<td align="center" width="30%">Email</td><td align="center" width="30%"><input type="text" name="email[]" id="email" style="margin-left:14px;"><a href="javascript:void(0);" title="Click here to add more mails" onclick="addNewRow('emailDiv', 'email',$('#emailDiv tr').length);" ><img src="../img/plus.png" border="0"></a></td>
							</tr>
           				<?php
           				}
           				?>
					</tbody> 
					<tr>
						<td align="center" width="30%">Urgency</td><td align="center" width="30%">
							<select name="problemType" id="problemType" style="width:234px; ">
								<option value="">Select Please....</option>
								<option value="<?php echo $value['problemType'];?>" <?php if($value['problemType'] == $value['problemType']){ echo 'selected';} ?>><?php echo $value['problemType'];?></option> 
								<option value="urgent">Urgent</option>
								<option value="normal">Normal</option>
							</select>
						</td>
					</tr>
					<tr>
						<td align="center" width="30%">Type of Product/Problem</td><td align="center" width="30%">
							<select name="productType" id="productType" style="width:234px; ">
								<option value="">Type of Product please....</option>
								<option value="<?php echo $value['productType'];?>" <?php if($value['productType'] == $value['productType']){ echo 'selected';} ?>><?php echo $value['productType'];?></option> 
								<option value="hardware">Hardware</option>
								<option value="software">Software</option>
								<option value="printer">Printer</option>
								<option value="ups">Ups</option>
							</select>
						</td>
					</tr>
					<tr>
						<td align="center" width="30%">Customer Problem</td><td align="center" width="30%">
							<textarea style="width:234px;height:130px;" name="complaint" id="complaint" value=""><?php echo $value['complaint'];?></textarea>	
						</td>
					</tr>
					<tr>
						<td align="center" width="30%">What have been done</td><td align="center" width="30%">
							<textarea style="width:234px;height:130px;" name="whenDone" id="whenDone" value=""><?php echo $value['whenDone'];?></textarea>	
						</td>
					</tr>
					<tr>
						<td align="center" width="30%">Finishing Date</td>
						<td align="center" width="30%"><input type="text" name="finishDate" id="finishDate" value="<?php echo $value['finishDate'];?>"></td>
					</tr>
					<tr>
						<td align="center" width="30%">Next Call</td>
						<td align="center" width="30%"><input type="text" name="nextCall" id="nextCall" value="<?php echo $value['nextCall'];?>"></td>
					</tr>
					<tr>
						<td align="center" width="30%">Assign To</td>
						<td align="center" width="30%">
							<select name="assignTo" id="assingTo" style="width:234px; ">
								<option value="">Name please....</option>
								<option value="<?php echo $value['assignTo'];?>" <?php if($value['assignTo'] == $value['assignTo']){ echo 'selected';} ?>><?php echo $value['assignTo'];?></option> 
								<option value="Sam">Sam</option>
								<option value="Shijin">Shijin</option>
								<option value="Sumesh">Sumesh</option>
								<option value="Baji">Baji</option>
							</select>					
						</td>
					</tr>
					<tr>
						<td align="center" width="30%">Status</td>
						<td align="center" width="30%">
							<table width="100%">
								<tr>
									<td>Pending<input type="radio" name="status" value="0" <?php if($value['status'] == '0'){echo "checked";}?>></td>
									<td>Solved<input type="radio" name="status" value="1" <?php if($value['status']== 1){echo "checked";}?>></td>
									<td>To company<input type="radio" name="status" value="2" <?php if($value['status']== 2){echo "checked";}?>></td>
									
								</tr>	
														
							</table>
						</td>
					</tr>
					<tr>
						<td align="center" width="30%" colspan="2">
						<input type="submit" value="update" name="submit">
						<a href="/service/list"><input type="button" value="Back"></a>
						</td>
					</tr>
					
				</table>
			</td>
		</tr>
		<?php
		}
		?>
	
	
	</table>
</form>