<script type="text/javascript" src="/js/jscolor.js"></script>
<style type="text/css">
.error{ color: red; font-size: 10px;}
</style>


<script type="text/javascript">
    $(document).ready(function()
    {
        // validate signup form on keyup and submit
        $("#addslider").validate({
            rules: {
                image_title: "required",
                field: "required",
               
            
            },
            messages: {
                image_title: "Title Please",
                field: "Image Please..",
            }
                    
        });

        $("#field").change(function()
        {
            var val = $("#field").val();
            switch(val.substring(val.lastIndexOf('.') + 1).toLowerCase())
            {
                case 'gif': case 'jpg': case 'png': case 'JPEG':
                    //alert("an image");
                break;
                default:
                $(this).val('');
                alert("Please upload an image with extension jpg,png,gif Only");
                break;
                return false;
            }
        });
        //<!-- image resiction code-->
        $('#field').change(function(e){
            var files=this.files;
            console.log(e,files);
            for (var i=0; i < files.length; i++) {
                var file=files[i];
                var imageType=/image.*/;
                if(!file.type.match(imageType)) {
                    continue;
                }

                var img=document.createElement("img");
                img.classList.add("obj");
                img.file=file;
                $("#container55").append(img);
                var reader=new FileReader();
                reader.onload=(function(aImg) {
                    return function(e) {
                        aImg.src=e.target.result;
                        aImg.addEventListener('load',function(){
                            var s=aImg.getBoundingClientRect();
                            if(s.width >501)
                            {
                                alert("please upload 500 X 280pixel images only");
                                $('#field').val('');
                                return false;
                            }
                            if( s.height > 281)
                            {
                                alert("please upload 500 X 280pixel images only");
                                 $('#field').val('');
                                return false;
                            }
                            
                        });
                    };
                })(img);
                reader.readAsDataURL(file);
            }
        }); 
        //<!-- image resiction code end-->
    });

        
</script>
<!-- image resiction code-->
<style>
    .obj{
visibility:hidden;
}
#container55{
width:500px;
height:280px;
position: absolute;
left: -9999px;
top: -9999px;
visibility: hidden;
}
</style>
<!-- image resiction code end -->


<div class="span9" id="content">
    <div class="row-fluid">

        <div class="navbar">
            <div class="navbar-inner">
                <ul class="breadcrumb">
                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <li>
                        <a href="">Dashboard</a> <span class="divider">/</span>	
                    </li>
                    <li>
                        <a href="">Home</a> <span class="divider">/</span>	
                    </li>
                    <li class="active"><a href="" >Add Slider</a></li>
                </ul>
            </div>
        </div>

        <a class="btn btn-primary " href="/admin/slider">List slider</a>
        <!--<a class="btn btn-primary " href="/superadmin/slider/add" border="0">Add slider</a>-->
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Slider Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addslider" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Image title </label>
                                    <div class="controls">
                                        <input type="text" name="image_title" id="image_title" class="span6">
                                        

                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="fileInput">Image input</label>
                                    <div class="controls">
                                        <input class="input-file uniform_on" id="field" type="file" name="field" multiple="multiple"><br/>
                                        <span style="font-size:10px; color:red;">Please upload 500 X 280 images</span>
                                        <br>
                                        <div id="container55"></div>
                                    </div>
                                </div>





                                <div class="control-group">
                                    <label class="control-label" for="textarea2">Image description</label>
                                    <div class="controls">
                                        <textarea name="image_description" id="image_description" placeholder="Enter text ..." style="width: 460px; height: 200px"></textarea>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Image link </label>
                                    <div class="controls">
                                        <input type="url" name="link" id="link" class="span6">

                                    </div>
                                </div>

                                
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/slider";
    });

</script>