<script type="text/javascript">

    
    $(document).ready(function() {
        showTable();
    });
    
    function showTable()
    {
        
        $.ajax({

            type:"POST",
            url:"/admin/slider/ajaxColorList",
            cache:false,
            data:{},
            dataType:"html",
            success:function(data)
            {
                //alert(data);//return;
                $("#ajx_table").html(data);
                //showTable(srt);
            }
        });
    }

    //patter Statusoff
    $('.spton').live('click',function()
    {
        var offId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/slider/patternStatus",
            cache:false,
            data:{ offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

    //patter On
    $('.stpof').live('click',function()
    {
        var onId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/slider/patternStatus",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

    // Statusoff
    $('.ston').live('click',function()
    {
        var offId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/slider/colorStatus",
            cache:false,
            data:{ offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

    //Status On
    $('.stof').live('click',function()
    {
        var onId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/slider/colorStatus",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                showTable();
            }
        });

    });

</script>
<style>
    .del{cursor:pointer;}.ston{cursor:pointer;}.stof{cursor:pointer;}stpon{cursor:pointer;}.stpof{cursor:pointer;}
</style>
<div class="span99" id="content">
    <div class="row-fluid">
        <div class="navbar">
            <div class="navbar-inner">
	            <ul class="breadcrumb">
	                <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
	                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
	                <li><a href="">Dashboard</a> <span class="divider">/</span></li>
	                <li><a href="">Home</a> <span class="divider">/</span></li>
	                <li class="active">Slider Color Settings</li>
	            </ul>
            </div>
        </div>
    </div>
                    
                   
    <div class="row-fluid">
        <div class="span12" style="min-height:400px;">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Slider Color Settings</div>
                    <a class="btn btn-primary " href="/admin/slider" border="0" style="float:right;">Go to Slider</a>
                    <div id="msg" style="font-size:12px; color:red; text-align:center;"></div>
                    <div class="pull-right">
                        <span class="badge badge-info"></span>
				    </div>
                </div>
                <div id="ajx_table"></div>
                  
            </div>
        </div>
               