<script type="text/javascript" src="/js/jscolor.js"></script>
<style type="text/css">
.error{ color: red; font-size: 10px;}
</style>


<script type="text/javascript">
    $(document).ready(function()
    {
        // validate signup form on keyup and submit
        $("#addslider").validate({
            rules: {
                image_title: "required",
                field: "required",
               
            
            },
            messages: {
                image_title: "Title Please",
                field: "Image Please..",
            }
                    
        });

        $("#field").change(function()
        {
            var val = $("#field").val();
            switch(val.substring(val.lastIndexOf('.') + 1).toLowerCase())
            {
                case 'gif': case 'jpg': case 'png': case 'JPEG':
                    //alert("an image");
                break;
                default:
                $(this).val('');
                alert("Please upload an image with extension jpg,png,gif Only");
                break;
                return false;
            }
        });
    });

        
</script>



<div class="span99" id="content">
    <div class="row-fluid">

        <div class="navbar">
            <div class="navbar-inner">
                <ul class="breadcrumb">
                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <li>
                        <a href="">Dashboard</a> <span class="divider">/</span> 
                    </li>
                    <li>
                        <a href="">Home</a> <span class="divider">/</span>  
                    </li>
                    <li class="active"><a href="" >Slider Color Settings</a></li>
                </ul>
            </div>
        </div>

        <a class="btn btn-primary " href="/admin/slider/color">List Slider Color</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Slider Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addslider" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                          
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Slider Backgrount color </label>
                                    <div class="controls">
                                        <input type="" name="c1" id="c1" class="color span6" id="link" >

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Slider Discription Backgrount color </label>
                                    <div class="controls">
                                        <input type="" name="c2" id="c2" class="color span6">

                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Slider Pattern Image</label>
                                    <div class="controls">
                                        <input type="file" name="f1" id="f1" class="span6">

                                    </div>
                                </div>

                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/slider";
    });

</script>