<script type="text/javascript">

    
    $(document).ready(function() {
        showTable();

    });
    
    function showTable()
    {
        
        $.ajax({

            type:"POST",
            url:"/admin/color/ajaxList",
            cache:false,
            data:{},
            dataType:"html",
            success:function(data)
            {
                $("#ajx_table").html(data);
            }
        });
    }

       
    
    //Status off
    $('.ston').live('click',function()
    {
        var offId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/color/status",
            cache:false,
            data:{offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                $('#msg').delay(2000).fadeOut();
                showTable();
            }
        });

    });

    //Status On
    $('.stof').live('click',function()
    {
        var onId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/color/status",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                $('#msg').delay(2000).fadeOut();
                showTable();
            }
        });

    });


    //default color Settings
    $('.ston_field').live('click',function()
    {
        var offId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/color/defaultStatus",
            cache:false,
            data:{offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                $('#msg').delay(2000).fadeOut();
                showTable();
            }
        });

    });

    //Status On
    $('.stof_field').live('click',function()
    {
        var onId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/color/defaultStatus",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                $('#msg').delay(2000).fadeOut();
                showTable();
            }
        });

    });


    //Color Picker
    //Status off
    $('.ston_picker').live('click',function()
    {
        var offId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/color/pickerStatus",
            cache:false,
            data:{offId:offId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                $('#msg').delay(2000).fadeOut();
                showTable();
            }
        });

    });

    //Status On
    $('.stof_picker').live('click',function()
    {
        var onId = $(this).attr('id'); 
        $.ajax({
            type:"POST",
            url:"/admin/color/pickerStatus",
            cache:false,
            data:{ onId:onId },
            dataType:"html",
            success:function(data)
            {
                $("#msg").html(data);
                $('#msg').delay(2000).fadeOut();
                showTable();
            }
        });

    });


   


</script>




<style type="text/css">
    .ston { cursor: pointer;} .stof { cursor: pointer;} .del { cursor: pointer;}

</style>

<div class="span99" id="content">
    <div class="row-fluid">
      	<div class="navbar">
           	
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left" style="text-align:center; float: left; width:100%;">Color Settings<div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>

                    
                </div>
                <div id="ajx_table"></div>
            </div>
        </div>
    </div>
                 