<script src="/js/jquery.validate.js"></script>


<script>
$().ready(function() {
    // validate the comment form when it is submitted
    $("#commentForm").validate();

    // validate signup form on keyup and submit
    $("#addProduct").validate({
        rules: {
            product_title: "required",
            product_description: "required",
            curl:"required",
            fileInput2:"required",
            
        },
        messages: {
            product_title: "Product title Please",
            product_description: "Product Details Please..",
            curl: "Url Please..",
            fileInput2:"image Please ..",
        }
                    
    });
    
    
        $("#fileInput2").change(function()
        {
            var val = $("#fileInput2").val();
            switch(val.substring(val.lastIndexOf('.') + 1).toLowerCase())
            {
                case 'gif': case 'jpg': case 'png': case 'JPEG':
                    //alert("an image");
                break;
                default:
                $(this).val('');
                alert("Please upload an image with extension jpg,png,gif Only");
                break;
                return false;
            }
        });
    
        //<!-- image resiction code-->
        $('#fileInput2').change(function(e){
            var files=this.files;
            console.log(e,files);
            for (var i=0; i < files.length; i++) {
                var file=files[i];
                var imageType=/image.*/;
                if(!file.type.match(imageType)) {
                    continue;
                }

                var img=document.createElement("img");
                img.classList.add("obj");
                img.file=file;
                $("#container55").append(img);
                var reader=new FileReader();
                reader.onload=(function(aImg) {
                    return function(e) {
                        aImg.src=e.target.result;
                        aImg.addEventListener('load',function(){
                            var s=aImg.getBoundingClientRect();
                            if(s.width >441)
                            {
                                alert("please upload 400 X 250pixel images only");
                                $('#fileInput2').val('');
                                return false;
                            }
                            if( s.height > 251)
                            {
                                alert("please upload 400 X 250pixel images only");
                                 $('#fileInput2').val('');
                                return false;
                            }
                            
                        });
                    };
                })(img);
                reader.readAsDataURL(file);
            }
        }); 
        //<!-- image resiction code end-->
        
        
   
           

$("#chk").show();
    $("#offHide").show();
    
    $('#chk').click(function(){
    $("#offHide").slideToggle();
    });
    
});


</script>
<style>
    .obj{
visibility:hidden;
}
#container55{
width:440px;
height:250px;
position: absolute;
left: -9999px;
top: -9999px;
visibility: hidden;
}
</style>

<style type="text/css">
#commentForm { width: 500px; }
#commentForm label { width: 250px; }
#commentForm label.error, #commentForm input.submit { margin-left: 253px; }
#signupForm { width: 670px; }
#signupForm label.error {
    margin-left: 10px;
    width: auto;
    display: inline;
}
#newsletter_topics label.error {
    display: none;
    margin-left: 103px;
}
.errors{color:red;}

</style>

<div class="span99" id="content">
    <div class="row-fluid">

        <div class="navbar">
            <div class="navbar-inner">
                <ul class="breadcrumb">
                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <li>
                        <a href="">Dashboard</a> <span class="divider">/</span> 
                    </li>
                    <li>
                        <a href="">Home</a> <span class="divider">/</span>  
                    </li>
                    <li class="active"><a href="" >Add Big Package</a>
                            <span style="font-size:12px;color:red;">
            <?php
            if(count($flashMessages))
            {
                foreach ($flashMessages as $msg)
                {
                    echo $msg.'</blink><br>';   
                }   
            }
            ?>
        </span>


                    </li>
                </ul>
            </div>
        </div>

        <a class="btn btn-primary " href="/admin/bigPackage">List Big Package</a>
        <!--<a class="btn btn-primary " href="/superadmin/slider/add" border="0">Add slider</a>-->
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Big Package Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Package title </label>
                                    <div class="controls">
                                        <input type="text" name="product_title" id="product_title" class="span6" id="typeahead" ><br />
                                    <span style="float: left;margin-top:9px;">
                                        If this Package is default One
                                        <input type="checkbox" name="default" value="1" style="margin-bottom:5px; margin-left:5px;" id="chk">
                                    </span>    

                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="textarea2">Package description</label>
                                    <div class="controls">
                                        <textarea name="product_description" id="product_description" placeholder="Enter text ..." style="width: 460px; height: 200px"></textarea>
                                    </div>
                                </div>

                                <!--<div class="control-group">
                                    <label class="control-label" for="fileInput">Package Image Big</label>
                                    <div class="controls">
                                        <input class="input-file uniform_on" id="fileInput1" type="file" name="field1"><br/>
                                        <span style="font-size:10px; color:red;">Please upload 500 X 280 images</span>
                                        <div id="container55"></div>
                                    </div>
                                </div>-->

                                <div class="control-group">
                                    <label class="control-label" for="fileInput">Package Image</label>
                                    <div class="controls">
                                        <input class="input-file uniform_on" id="fileInput2" type="file" name="field2" required><br/>
                                        <span style="font-size:10px; color:red;">Please upload 440 X 250 images</span>
                                        <div id="container55"></div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Package link </label>
                                    <div class="controls">
                                        <input type="url" name="curl" class="span6" id="curl" >

                                    </div>
                                </div>
                                <div id="offHide">
                                    <div class="control-group">
                                        <label class="control-label" for="typeahead">Offer from </label>
                                        <div class="controls">
                                             <input type="text" name="pre-select-dates" id="pre-select-dates" class="box"/>
                                            <script>                            
                                                var today = new Date();
                                                var y = today.getFullYear();
                                                $('#pre-select-dates').multiDatesPicker();
                                            </script>
                                        
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/bigPackage";
    });

</script>