<div class="span999" id="content">
    <div class="row-fluid">
        <div class="navbar">
            <div class="navbar-inner">
	            <ul class="breadcrumb">
	                <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
	                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
	                <li><a href="">Dashboard</a> <span class="divider">/</span></li>
	                <li><a href="">Home</a> <span class="divider">/</span></li>
	                <li class="active">Mailed List</li>

	            </ul>
            </div>
        </div>
    </div>
                    
                   
    <div class="row-fluid">
        <div class="span12" style="min-height:400px;">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">
                        Home Menu
                    </div>
                    <div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>
                    <div class="pull-right"><span class="badge badge-info"></span>
				</div>
            </div>
              <div class="block-content collapse in">
              <?php
                $cnt= count($contactUserTable);
                if($cnt != '')
                {
                ?>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Mailed date</th>
                                <th>Company Name</th>
                                <th>Contact Person</th>
                                <th>Phone No</th>
                                <th>Email</th>
                                <th>Interested In</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        
                            foreach ($contactUserTable as $key => $value)
                            {
                                $s= explode("_", $value['interested_in']);
                                ?>                         
                                <tr>
                                    <td><?php echo $value['created_on'];?></td>
                                    <td><?php echo $value['comp_name'];?></td>
                                    <td><?php echo $value['cont_person'];?></td>
                                    <td><?php echo $value['cont_phone'];?></td>
                                    <td><?php echo $value['cont_email'];?></td>
                                    <td>
                                        <?php
                                            if($s[0] != '')
                                            { 
                                                echo $s[0].'<br>';
                                            }
                                            if($s[1] != '')
                                            {
                                                echo $s[1].'<br>';
                                            }
                                            if($s[2] != '')
                                            {
                                                echo $s[2].'<br>';
                                            }
                                            if($s[3] != '')
                                            {
                                                echo $s[3].'<br>';
                                            }
                                            if($s[4] != '')
                                            {
                                                echo $s[4];
                                            }
                                            
                                        ?>
                                    </td>
                                </tr>
                                <?php
                            }
                        ?>
                   </tbody>
                </table>
                <?php
                }
                else
                {
                    echo "Oops no result found....";
                }
                ?>
        </div>
        
    </div>
</div>
               