<script type="text/javascript">
    $(document).ready(function ()
    {
        $('#msg').delay(2000).fadeOut();
    });
</script>

<div class="span999" id="content">
    <div class="row-fluid">
        <div class="navbar">
            <div class="navbar-inner">
	            <ul class="breadcrumb">
	                <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
	                <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
	                <li><a href="">Dashboard</a> <span class="divider">/</span></li>
	                <li><a href="">Home</a> <span class="divider">/</span></li>
	                <li class="active">Send Mail Settings</li>

	            </ul>
            </div>
        </div>
    </div>
                    
                   
    <div class="row-fluid">
        <div class="span12" style="min-height:400px;">
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">
                        Home Menu
                    </div>
                    <div id="msg" style="font-size:12px; color:red; text-align:center;">
                        <?php
                            if(count($flashMessages))
                            {
                                foreach ($flashMessages as $msg)
                                {
                                    echo $msg.'</blink><br>';   
                                }   
                            }
                        ?>
                    </div>
                    <div class="pull-right"><span class="badge badge-info"></span>
				</div>
            </div>
              <div class="block-content collapse in">
              <?php
                $cnt= count($useremail);
                if($cnt != '')
                {
                ?>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th style="text-align:center">Send Mail</th>
                                <th style="text-align:center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        
                            foreach ($useremail as $key => $value)
                            {
                                ?>                         
                                <tr>
                                    <td style="text-align:center"><?php echo $value['email'];?></td>
                                    <td style="text-align:center"><a href="/admin/mailedList/edit/<?php echo $value['id']; ?>" style="text-decoration:none;"><img src="/images/edit.png" border="0" width="20" height="20"></a></td>
                                </tr>
                                <?php
                            }
                        ?>
                   </tbody>
                </table>
                <?php
                }
                else
                {
                    echo "Oops no result found....";
                }
                ?>
        </div>
        
    </div>
</div>
               