<style type="text/css">
#commentForm { width: 500px; }
#commentForm label { width: 250px; }
#commentForm label.error, #commentForm input.submit { margin-left: 253px; }
#signupForm { width: 670px; }
#signupForm label.error {
	margin-left: 10px;
	width: auto;
	display: inline;
}
#newsletter_topics label.error {
	display: none;
	margin-left: 103px;
}
</style>

<div class="span9" id="content">
    <div class="row-fluid">

        <div class="navbar">
            <div class="navbar-inner">
                <ul class="breadcrumb">
                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <li>
                        <a href="home.php">Dashboard</a> <span class="divider">/</span>	
                    </li>
                    <li>
                        <a href="home.php">Home</a> <span class="divider">/</span>	
                    </li>
                    <li class="active"><a href="" >Add new Count Master</a></li>
                </ul>
            </div>
        </div>

        <a class="btn btn-primary " href="/superadmin/menu">List Master</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Counts Master Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addslider" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Item </label>
                                    <div class="controls">
                                        <input type="text" name="item" id="item" class="span6" id="typeahead" >
                                        

                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Count </label>
                                    <div class="controls">
                                        <input type="text" name="count" id="count" class="span6" id="typeahead" >
                                        

                                    </div>
                                </div>



                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/superadmin/countMaster";
    });

</script>