<style type="text/css">
#commentForm { width: 500px; }
#commentForm label { width: 250px; }
#commentForm label.error, #commentForm input.submit { margin-left: 253px; }
#signupForm { width: 670px; }
#signupForm label.error {
	margin-left: 10px;
	width: auto;
	display: inline;
}
#newsletter_topics label.error {
	display: none;
	margin-left: 103px;
}
</style>
<script type="text/javascript">
    $(document).ready(function()
    {

        // validate signup form on keyup and submit
        $("#addPages").validate({
            rules: {
                title: "required",
                sub_title: "required",
                dis:"required",
            
            },
            messages: {
                title: "Title Please",
                sub_title: "Subtitle Please..",
                dis: "Discription Please..",
            }
                    
        });


        //Form Validation
        /*$('#addMenu').click(function()
        {
            if($("#menu_url").val() !='')
            {
                var con = $("#menu_url").val();
                var controller = $("#controller").val();
                var myNewString = con.replace("http://", "");
                alert(myNewString);
                var myarr = myNewString.split("/");
                if(myarr[1] != controller)
                {
                    alert("Soryy Controller name is not equal to ")
                } 
            }
        });*/
    });

    
</script>


<div class="span9" id="content">
    <div class="row-fluid">

        <div class="navbar">
            <div class="navbar-inner">
                <ul class="breadcrumb">
                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <li>
                        <a href="">Dashboard</a> <span class="divider">/</span>	
                    </li>
                    <li>
                        <a href="">Home</a> <span class="divider">/</span>	
                    </li>
                    <li class="active"><a href="#" >Add Pages</a></li>
                </ul>
            </div>
        </div>

        <a class="btn btn-primary " href="/admin/pages">List Pages</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Pages Form</div>
                    <span style="font-size:12px;color:red; margin-left:160px; float:left;">
                        <?php
                        if(count($flashMessages))
                        {
                            foreach ($flashMessages as $msg)
                            {
                                echo "<br>".$msg;   
                            }   
                        }
                        ?>
                    </span>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addPages" name="addPages" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                                <?php
                                foreach ($editPageData as $key => $value)
                                {
                                ?>
                                   
                                    <div class="control-group">
                                        <label class="control-label" for="typeahead">Title </label>
                                        <div class="controls">
                                            <input type="text" name="title" id="title" class="span6" value="<?php echo $value['title'];?>" >
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="typeahead">Sub Title</label>
                                        <div class="controls">
                                            <input type="text" name="sub_title" id="sub_title" class="span6" value="<?php echo $value['sub_title'];?>" >
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="typeahead">Description</label>
                                        <div class="controls">
                                            <textarea name="dis" id="dis" style="width:323px; height:100px;"><?php echo $value['description'];?>"</textarea>
                                        </div>
                                    </div>  
                                    <div class="control-group">
                                    <label class="control-label" for="typeahead">Link</label>
                                    <div class="controls">
                                         <input type="text" name="url" id="url" class="span6" value="<?php echo $value['url'];?>" >
                                    </div>
                                </div>                             
                                    <div class="form-actions">
                                        <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                        <button type="reset" class="btn" id="cancel">Cancel</button>
                                    </div>
                                <?php
                                }
                                ?>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/pages";
    });

</script>