<script src="/js/jquery.validate.js"></script>


<script>
$().ready(function() {
    
    $("#addProduct").validate({
        rules: {           
            service_pagename: "required",
            service_template: "required",
                      
//            field:
//            {
//                required: true,
//                accept:"jpeg|gif|jpg",
//            }  
        },
        messages: {          
            service_pagename: "Service Title Please",
            service_template: "Service Link Please",                   
//            field:
//            {
//                required: "Service Image Please",
//                accept: "Only image type jpg/jpeg/gif is allowed",
//            }  
        },
                    
    });

    
});
</script>


<style type="text/css">
#commentForm { width: 500px; }
#commentForm label { width: 250px; }
#commentForm label.error, #commentForm input.submit { margin-left: 253px; }
#signupForm { width: 670px; }
#signupForm label.error {
    margin-left: 10px;
    width: auto;
    display: inline;
}
#newsletter_topics label.error {
    display: none;
    margin-left: 103px;
}
.errors{color:red;}
</style>
<?php foreach($servicePage as $service)?>
<div class="span12" id="content">
    <div class="row-fluid">

        <div class="navbar">
            <div class="navbar-inner">
                <ul class="breadcrumb">
                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <li>
                        <a href="">Dashboard</a> <span class="divider">/</span> 
                    </li>
                    <li>
                        <a href="">Home</a> <span class="divider">/</span>  
                    </li>
                    <li class="active"><a href="" >Edit Services Page Title</a> </li>
                </ul>
            </div>
        </div>

        <a class="btn btn-primary " href="/admin/servicespage">List Service pages</a>
        <!--<a class="btn btn-primary " href="/superadmin/slider/add" border="0">Add slider</a>-->
    </div>


    <div class="row-fluid">
        <div class="span12">
            <!-- block - -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Other Services Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addProduct" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Edit Services Page Title</legend>

                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Title</label>
                                    <div class="controls">
                                        <input type="text" name="service_pagename" id="service_pagename" class="span6" id="typeahead" value="<?=$service['page_name'];?>" ><br />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="textarea2">Select Template </label>
                                    <div class="controls">
                                        <select class="span6" name="service_template" id="service_template">
                                            <option value="">Select Template</option>
                                            <?php foreach($serviceTemplate as $serviceValue){?>
                                            <option value="<?=$serviceValue['id'];?>" <?php if($serviceValue['id']==$service['page_template']) echo 'selected';?>><?=$serviceValue['template_name'];?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>

                                
                                
                                <div class="control-group">
                                         <span style="font-size:14px; color:red;">                                          
                                          
                                                <?php
                                                if(count($flashMessages))
                                                {
                                                    foreach ($flashMessages as $msg)
                                                    {
                                                        echo $msg.'</blink><br>';   
                                                    }   
                                                }
                                                ?>
                            
                                        </span>
                                   
                                </div>
                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath().'/admin/servicespage/'.$serviceId;?>";
    });

</script>