<script language="text/javascript">
    function delSer(passId){
        var retVal=confirm('Delete...Are you sure?');
        if(retVal==true){           
            $.ajax({
            type:'POST',
            url :'<?php echo $this->basePath().'/admin/servicespagetemplate/delete';?>',
            data:{delId:passId},
            success:function(data){
                //alert(data);
             }
            })
        }
        else{
            location.redirect();
        }
        
    }
</script>
<div class="block-content collapse in">
    <?php $cnt= count($listPageTemplates);
            if($cnt==0){
                echo 'No Result Found';
            }
            else{
           
    ?>
              <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>S.No</th>
                            <th width="120">Template Name</th>
                            <th>Page Template</th>
                            <th>Edit</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    
                    foreach ($listPageTemplates as $key => $value)
                    {
          
                        ?>                         
    	                <tr>
    	                	<td><?php echo $key+1;?></td>
                            <td width="120"><?php
                                $s=strlen($value['template_name']);
                                if($s >20)
                                {
                                    echo substr($value['template_name'],0,20).".....";
                                }
                                else
                                {
                                    echo $value['template_name'];
                                }
                                ?>

                            </td>
                            <td>
                                <?php echo $value['service_template'];?>
                            </td>
    	                   
    	                    
    	                    <td>
    	                    	<a href="/admin/servicespagetemplate/edit/<?php echo $value['id']; ?>" style="text-decoration:none;"><img src="/images/edit.png" border="0" width="20" height="20"></a>
    	                    </td>
                            <td>
                                <img onclick="delSer(<?php echo $value['id']; ?>)" src="/images/delete.png" id="" border="0" width="20" height="20" class="del" />
                                 <!--href="/admin/otherservices/delete/<?php //echo $value['id']; ?>"-->
                            </td>
    	                </tr>
                        <?php
                    }
                    ?>
               </tbody>
            </table>
            <?php }?>
        </div>