<style type="text/css">
#commentForm { width: 500px; }
#commentForm label { width: 250px; }
#commentForm label.error, #commentForm input.submit { margin-left: 253px; }
#signupForm { width: 670px; }
#signupForm label.error {
	margin-left: 10px;
	width: auto;
	display: inline;
}
#newsletter_topics label.error {
	display: none;
	margin-left: 103px;
}
</style>
<script type="text/javascript">
    $(document).ready(function()
    {
        $("#commentForm").validate();

        // validate signup form on keyup and submit
        $("#addCountry").validate({
            rules: {
               country: "required",            
            },
            messages: {
                country: "Country Please",
            }
                    
        });
    });

</script>

<div class="span9" id="content">
    <div class="row-fluid">

        <div class="navbar">
            <div class="navbar-inner">
                <ul class="breadcrumb">
                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                    <li>
                        <a href="">Dashboard</a> <span class="divider">/</span>	
                    </li>
                    <li>
                        <a href="">Home</a> <span class="divider">/</span>	
                    </li>
                    <li class="active"><a href="/admin/contacts/add" >Add New Contacts</a></li>
                </ul>
            </div>
        </div>

        <a class="btn btn-primary " href="/admin/contacts">List Master</a>
    </div>


    <div class="row-fluid">
        <div class="span12">

            <!-- block - -->

            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Contacts Master Form</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form class="form-horizontal" id="addContacts" name="addContacts" method="post" enctype="multipart/form-data">
                            <fieldset>
                                <legend>Form Components</legend>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Country</label>
                                    <div class="controls">
                                        <select name="country" id="country">
                                            <option value="">Please select</option>
                                            <?php foreach ($country as $key => $value)
                                            {
                                            ?>
                                           <option value="<?php echo  $this->escapeHtml($value['id']);?>"><?php echo $value['country']; ?></option>
                                            <?php
                                        }
                                        ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Title </label>
                                    <div class="controls">
                                        <input type="text" name="title" id="title" class="span6" >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Description</label>
                                    <div class="controls">
                                       <textarea name="description" id="description" placeholder="Enter text ..." style="width: 460px; height: 200px"></textarea>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Phone </label>
                                    <div class="controls">
                                        <input type="text" name="phone" id="phone" class="span6" >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Info Email </label>
                                    <div class="controls">
                                        <input type="text" name="info" id="info" class="span6" >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="typeahead">Service Email </label>
                                    <div class="controls">
                                        <input type="text" name="service" id="service" class="span6" >
                                    </div>
                                </div>
                                

                                <div class="form-actions">
                                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    <button type="reset" class="btn" id="cancel">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->


        </div>

    </div>

</div>
</div>
<script type="text/javascript">
    $("#cancel").click(function()
    {
        window.location.href= "<?php echo $this->basePath()?>/admin/contacts";
    });

</script>